#!/usr/bin/env python
"""Generate responsive hero images (AVIF + WebP + JPEG) at multiple widths.

Workflow:
    1. Drop a full-quality original (>= 3840 px wide, landscape) into
       frontend/hero-src/  — e.g. hero-laboe.jpeg
    2. Run:  python scripts/gen_hero.py
    3. Optimized variants land in frontend/public/ and a manifest is written
       to frontend/src/heroManifest.ts, which <HeroImage> consumes.

Requirements:  pip install Pillow pillow-avif-plugin

Never upscales: variants are capped at the source width and at MAX_WIDTH
(3840), so Retina/4K displays are covered without invented pixels.
"""
from __future__ import annotations
import json
import os
from pathlib import Path

from PIL import Image

try:
    import pillow_avif  # noqa: F401  (registers the AVIF plugin)
    HAS_AVIF = True
except Exception:
    HAS_AVIF = False

HERE = Path(__file__).resolve().parent
SRC_DIR = HERE.parent / "hero-src"
OUT_DIR = HERE.parent / "public"
MANIFEST = HERE.parent / "src" / "heroManifest.ts"

MAX_WIDTH = 3840
LADDER = [1280, 1920, 2560, 3840]
SRC_EXT = {".jpg", ".jpeg", ".png"}

# Quality per format (visually close, very different byte cost).
AVIF_Q, WEBP_Q, JPEG_Q = 55, 82, 85
# Formats in <picture> preference order (best first).
FORMATS = (["avif"] if HAS_AVIF else []) + ["webp", "jpg"]


def target_widths(src_w: int) -> list[int]:
    ws = [w for w in LADDER if w < src_w]
    ws.append(min(src_w, MAX_WIDTH))
    return sorted({w for w in ws if w <= MAX_WIDTH})


def save(im: Image.Image, path: Path, fmt: str) -> None:
    if fmt == "avif":
        im.save(path, "AVIF", quality=AVIF_Q, speed=5)
    elif fmt == "webp":
        im.save(path, "WEBP", quality=WEBP_Q, method=6)
    else:
        im.save(path, "JPEG", quality=JPEG_Q, optimize=True, progressive=True)


def process(src: Path) -> tuple[str, dict]:
    base = src.stem  # e.g. "hero-laboe"
    im = Image.open(src).convert("RGB")
    src_w, src_h = im.size
    widths = target_widths(src_w)

    for w in widths:
        h = round(src_h * w / src_w)
        resized = im if w == src_w else im.resize((w, h), Image.LANCZOS)
        for fmt in FORMATS:
            save(resized, OUT_DIR / f"{base}-{w}.{fmt}", fmt)

    # <img> fallback: the width closest to 1920 as a sensible default.
    fb_w = min(widths, key=lambda w: abs(w - 1920))
    entry = {
        "widths": widths,
        "formats": FORMATS,
        "fallback": f"/{base}-{fb_w}.jpg",
    }
    print(f"{src.name}: {src_w}x{src_h} -> widths {widths}  formats {FORMATS}")
    return base, entry


def main() -> None:
    if not SRC_DIR.exists():
        raise SystemExit(f"No source dir: {SRC_DIR}")
    if not HAS_AVIF:
        print("! pillow-avif-plugin not installed — AVIF skipped (WebP+JPEG only)")

    manifest: dict[str, dict] = {}
    for src in sorted(SRC_DIR.iterdir()):
        if src.suffix.lower() in SRC_EXT:
            base, entry = process(src)
            manifest[base] = entry

    header = (
        "// AUTO-GENERATED by scripts/gen_hero.py — do not edit by hand.\n"
        "export interface HeroVariant {\n"
        "  widths: number[];\n"
        "  formats: string[];\n"
        "  fallback: string;\n"
        "}\n\n"
        "export const heroManifest: Record<string, HeroVariant> =\n"
    )
    MANIFEST.write_text(header + json.dumps(manifest, indent=2) + ";\n", encoding="utf-8")
    print(f"\nManifest -> {MANIFEST}")


if __name__ == "__main__":
    main()
