// AUTO-GENERATED by scripts/gen_hero.py — do not edit by hand.
export interface HeroVariant {
  widths: number[];
  formats: string[];
  fallback: string;
}

export const heroManifest: Record<string, HeroVariant> =
{
  "hero-surfwind": {
    "widths": [
      1280,
      1920,
      2560
    ],
    "formats": [
      "webp",
      "jpg"
    ],
    "fallback": "/hero-surfwind-1920.jpg"
  },
  "hero-laboe": {
    "widths": [
      1280,
      1920,
      2250
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "fallback": "/hero-laboe-1920.jpg"
  },
  "hero-welle": {
    "widths": [
      1280,
      1920,
      2560,
      3840
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "fallback": "/hero-welle-1920.jpg"
  },
  "hero-wind": {
    "widths": [
      1280,
      1920,
      2560,
      3840
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "fallback": "/hero-wind-1920.jpg"
  }
};
